
package Slider;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristina
 */
public class Puzzle extends javax.swing.JFrame {

     int secondsPassed =0;
     int moves = 1;
    
      //Creates new form Puzzle
     
    public Puzzle() {
        initComponents();
        setLocationRelativeTo(null);
        btn9.setVisible(false); // set button tile visibility to false
  
    }
    
    Timer timer = new Timer(); // set up timer
    TimerTask task = new TimerTask(){
        public void run(){
            secondsPassed++;
            timeText.setText(String.valueOf(secondsPassed));
            System.out.println("Seconds passed:" + secondsPassed);
        
        }
    };
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRand = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        timeText = new javax.swing.JTextField();
        moveText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Slider Puzzle");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel3)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 100));

        btnRand.setBackground(new java.awt.Color(0, 0, 0));
        btnRand.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRand.setForeground(new java.awt.Color(255, 255, 255));
        btnRand.setText("Randomize");
        btnRand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Time:");

        timeText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        moveText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Moves:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveText, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(timeText, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnRand))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(timeText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(moveText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btnRand, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3, 3, 3));

        btn1.setBackground(new java.awt.Color(153, 204, 255));
        btn1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setBackground(new java.awt.Color(51, 102, 255));
        btn2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setBackground(new java.awt.Color(204, 102, 255));
        btn3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        btn4.setBackground(new java.awt.Color(255, 0, 153));
        btn4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setBackground(new java.awt.Color(255, 255, 102));
        btn5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setBackground(new java.awt.Color(255, 153, 51));
        btn6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        btn7.setBackground(new java.awt.Color(255, 102, 204));
        btn7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setBackground(new java.awt.Color(0, 153, 153));
        btn8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setBackground(new java.awt.Color(102, 255, 102));
        btn9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //timer start 
    public void start(){  
    timer.scheduleAtFixedRate(task, 0, 1000);
    
    }
    
    //timer stop
    public void stop(){
        timer.cancel();
        
    }
    
    
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        
        if(btn2.isVisible()==false){ //if tile to the right of Tile one is not visible move Tile one to the right
        btn2.setText(btn1.getText());
        btn1.setVisible(false);
        btn2.setVisible(true);
        }
          if(btn4.isVisible()==false){ // do the same if tile is not visible 
        btn4.setText(btn1.getText());
        btn1.setVisible(false);
        btn4.setVisible(true);
        }
          countMoves(); //keep track of moves
          youWon(); // if in order output you won
    }//GEN-LAST:event_btn1ActionPerformed
  
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        
         if(btn1.isVisible()==false){ // same for the rest of these. visibility depends on the surrounding tiles 
        btn1.setText(btn2.getText());
        btn2.setVisible(false);
        btn1.setVisible(true);
        }
          if(btn3.isVisible()==false){
        btn3.setText(btn2.getText());
        btn2.setVisible(false);
        btn3.setVisible(true);
        }
          if(btn5.isVisible()==false){
        btn5.setText(btn2.getText());
        btn2.setVisible(false);
        btn5.setVisible(true);
        }
          countMoves();
          youWon();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if(btn2.isVisible()==false){
        btn2.setText(btn3.getText());
        btn3.setVisible(false);
        btn2.setVisible(true);
        }
          if(btn6.isVisible()==false){
        btn6.setText(btn3.getText());
        btn3.setVisible(false);
        btn6.setVisible(true);
        }
          countMoves();
          youWon();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if(btn1.isVisible()==false){
        btn1.setText(btn4.getText());
        btn4.setVisible(false);
        btn1.setVisible(true);
        }
        if(btn7.isVisible()==false){
        btn7.setText(btn4.getText());
        btn4.setVisible(false);
        btn7.setVisible(true);
        }
        if(btn5.isVisible()==false){
        btn5.setText(btn4.getText());
        btn4.setVisible(false);
        btn5.setVisible(true);
        }
        countMoves();
        youWon();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
         if(btn2.isVisible()==false){
        btn2.setText(btn5.getText());
        btn5.setVisible(false);
        btn2.setVisible(true);
        }
        if(btn6.isVisible()==false){
        btn6.setText(btn5.getText());
        btn5.setVisible(false);
        btn6.setVisible(true);
        }
        if(btn8.isVisible()==false){
        btn8.setText(btn5.getText());
        btn5.setVisible(false);
        btn8.setVisible(true);
        }
        if(btn4.isVisible()==false){
        btn4.setText(btn5.getText());
        btn5.setVisible(false);
        btn4.setVisible(true);
        }
        countMoves();
        youWon();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if(btn9.isVisible()==false){
        btn9.setText(btn6.getText());
        btn6.setVisible(false);
        btn9.setVisible(true);
        }
         if(btn3.isVisible()==false){
        btn3.setText(btn6.getText());
        btn6.setVisible(false);
        btn3.setVisible(true);
        }
          if(btn5.isVisible()==false){
        btn5.setText(btn6.getText());
        btn6.setVisible(false);
        btn5.setVisible(true);
        }
          countMoves();
          youWon();
         
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
         if(btn4.isVisible()==false){
        btn4.setText(btn7.getText());
        btn7.setVisible(false);
        btn4.setVisible(true);
        }
        if(btn8.isVisible()==false){
        btn8.setText(btn7.getText());
        btn7.setVisible(false);
        btn8.setVisible(true);
        }
        countMoves();
        youWon();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        
        if(btn9.isVisible()==false){
        btn9.setText(btn8.getText());
        btn8.setVisible(false);
        btn9.setVisible(true);
        }
        if(btn7.isVisible()==false){
            btn7.setText(btn8.getText());
            btn8.setVisible(false);
            btn7.setVisible(true);
        }
        if(btn5.isVisible()==false){
            btn5.setText(btn8.getText());
             btn8.setVisible(false);
            btn5.setVisible(true);
        }
        countMoves();
        youWon();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
         if(btn6.isVisible()==false){
        btn6.setText(btn9.getText());
        btn9.setVisible(false);
        btn6.setVisible(true);
        }
        if(btn8.isVisible()==false){
        btn8.setText(btn9.getText());
        btn9.setVisible(false);
        btn8.setVisible(true);
        }
        countMoves();
        youWon();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnRandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandActionPerformed
        
        randomize();
    }//GEN-LAST:event_btnRandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puzzle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnRand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField moveText;
    private javax.swing.JTextField timeText;
    // End of variables declaration//GEN-END:variables

    public void countMoves(){ 
        moveText.setText(String.valueOf(moves++));
        
       if(moves==1){
       start();
       }
        
    }

    public void randomize(){
        moveText.setText(String.valueOf(moves=0)); // SET BACK TO ZERO MOVES 
       // start();
        
        ArrayList<String> numbers = new ArrayList<String>(); //create array list so they can be shuffled
        
      //List numbers = new ArrayList();
       
      numbers.add(btn1.getText());
      numbers.add(btn2.getText());
      numbers.add(btn3.getText());
      numbers.add(btn4.getText());
      numbers.add(btn5.getText());
      numbers.add(btn6.getText());
      numbers.add(btn7.getText());
      numbers.add(btn8.getText());
      //numbers.add(btn9.getText());
      
      System.out.println(btn1.getText());
      Collections.shuffle(numbers);
      
      
     // System.out.println("nums" + numbers.get(1));
      //System.out.println("numbers" + numbers);
       
      
        btn1.setText(numbers.get(0)); //print out to the tile from shuffled arraylist
        btn2.setText(numbers.get(1));
        btn3.setText(numbers.get(2));
        btn4.setText(numbers.get(3));
        btn5.setText(numbers.get(4));
        btn6.setText(numbers.get(5));
        btn7.setText(numbers.get(6));
        btn8.setText(numbers.get(7));
        
      
       
    }
   
    public void youWon(){ 
        
        //
        String tile1 = btn1.getText();
        String tile2 = btn2.getText();
        String tile3 = btn3.getText();
        String tile4 = btn4.getText();
        String tile5 = btn5.getText();
        String tile6 = btn6.getText();
        String tile7 = btn7.getText();
        String tile8 = btn8.getText();
        
       if(tile1=="1" && tile2=="2" && tile3=="3" && tile4=="4" && tile5=="5" && tile6=="6" && tile7=="7" && tile8=="8"){
          JOptionPane.showMessageDialog(this,"You Have Won!");
          stop(); //stop time
       }
    }
}
